name = "ASEPotential"
uuid = "756cd54d-5d9c-4a09-a510-9b20339e7260"
authors = ["Jeremiah DeGreeff <degreeff@mit.edu> and contributors"]
version = "0.2.0"

[deps]
Atomistic = "3e762ff9-b8d8-45cf-a902-edcbc7124e71"
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
InteratomicPotentials = "a9efe35a-c65d-452d-b8a8-82646cd5cb04"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Atomistic = "0.3"
AtomsBase = "0.2"
InteratomicPotentials = "0.1"
PyCall = "1"
StaticArrays = "1"
Unitful = "1"
julia = "1"

[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
